language: php

sudo: required

php:
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
  - sudo apt-add-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - touch .env

before_script:
  - pecl channel-update pecl.php.net
  - pecl install libsodium-1.0.6
  - composer install --dev --no-interaction

after_script:
  - php vendor/bin/coveralls -v


script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls